jobs:
- job: 'Style'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
      architecture: 'x64'
      versionSpec: '3.8'
      architecture: 'arm64'
  - script: |
      pip install tox
      tox -e style
    displayName: 'tox -e style'

- job: 'Test'
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      Python38:
        python.version: '3.8'
    maxParallel: 4

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
      versionSpec: '3.8'
      architecture: 'arm64'

  - script: |
      pip install wheel
      pip install tox tox-docker
      tox -e py38
    displayName: 'tox'
